
before_script:

.build-template:
  image: forthy42/gforth-builder-linux-$ARCH:$DISTRIBUTION
  script:
    - ./install-deps.sh $DISTRIBUTION $ARCH
    - ./autogen.sh
    - case $ARCH in
      i386)
        export BARCH=i686
        ;;
      amd64)
        export BARCH=x86_64
        ;;
      esac
    - ./configure --host=$BARCH-pc-linux-gnu --build=$BARCH-pc-linux-gnu
    - make -j`nproc` libs
    - make install-libs
    - make distclean
    - for i in bdelta keccak-low threefish ed25519-donna; do (cd $i; dpkg-buildpackage -uc -us -d -b -a$ARCH); done
    - dpkg-buildpackage -uc -us -d -b -a$ARCH
    - mkdir -p debian/$DISTRIBUTION/$ARCH
    - rm -f debian/$DISTRIBUTION/$ARCH/*.deb
    - mv ../*.deb *.deb debian/$DISTRIBUTION/$ARCH/
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - debian/$DISTRIBUTION/$ARCH/*.deb

build:
  extends: .build-template
  parallel:
    matrix:
      - DISTRIBUTION: [unstable, stable, oldstable]
        ARCH: [amd64, i386]
