
before_script:
 
stages:
  - build-amd64
  - build-i386

build-amd64:
  stage: build-amd64
  image: forthy42/gforth-builder-linux-amd64:unstable
  script:
    - ./install-deps.sh unstable
    - ./autogen.sh
    - ./configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu
    - make -j`nprocs` libs
    - make install-libs
    - make distclean
    - for i in bdelta keccak-low threefish ed25519-donna; do (cd $i; dpkg-buildpackage -uc -us -d -b)
    - dpkg-buildpackage -uc -us -d -b
    - rm -f debian/*.deb
    - mv ../*.deb *.deb debian
  
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - debian/*.deb

build-i386:
  stage: build-i386
  image: forthy42/gforth-builder-linux-i386:unstable
  script:
    - ./install-deps.sh unstable
    - ./autogen.sh
    - ./configure --host=i686-pc-linux-gnu --build=i686-pc-linux-gnu
    - make -j`nprocs` libs
    - make install-libs
    - make distclean
    - for i in bdelta keccak-low threefish ed25519-donna; do (cd $i; dpkg-buildpackage -uc -us -d -b)
    - dpkg-buildpackage -uc -us -d -b -ai386
    - mv ../*i386*.deb debian
  
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - debian/*.deb

