#!/bin/bash
set -v
NACLREV=20110221
NACLPATCH=nacl.diff
if [ ! -f nacl-$NACLREV.tar.bz2 ]
then
    wget http://hyperelliptic.org/nacl/nacl-$NACLREV.tar.bz2
    bunzip2 < nacl-$NACLREV.tar.bz2 | tar -xf -
    if [ -f "$NACLPATCH" ]
    then
	patch -p0 -s <$NACLPATCH
    fi
fi
cd nacl-$NACLREV
./do
cd build/$HOST/lib/amd64
ar r libnacl.a cpucycles.o randombytes.o
sudo cp libnacl.a /usr/local/lib64
cd ../../include
sudo cp -r amd64 /usr/local/include
